name: rtd312
dependencies:
  - pip==24.2
  - python=3.12
  - sphinx-book-theme==1.1.2
  - sphinx-copybutton==0.5.2
  - sphinx-design==0.6.1
  - sphinx-immaterial==0.12.4
  - sphinx-material==0.0.36
  - sphinx==8.1.3
  - pip:
      - sphinx-immaterial[keys]
