name: rtd311
dependencies:
  - python=3.11
  - pip==24.2
  - sphinx==8.1.3
  - pip:
      - sphinx-book-theme==1.1.2
      - sphinx-copybutton==0.5.2
      - sphinx-material==0.0.36
      - sphinx-design==0.6.1
      - sphinx-immaterial==0.12.4
      - sphinx-immaterial[keys]
