name: rtd312
dependencies:
  - pip=24.2
  - python=3.12
  - conda-forge::sphinx-book-theme=1.1.2
  - conda-forge::sphinx-copybutton=0.5.2
  - conda-forge::sphinx-design=0.6.1
  - conda-forge::sphinx-immaterial=0.12.4
  - conda-forge::sphinx-material=0.0.36
  - conda-forge::sphinx=8.1.3
  - pip:
      - sphinx-immaterial[keys]
